# Configuración para Nginx (Single Page Application)
server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    index index.html;

    # Todas las rutas redirigen al index.html para que React Router se encargue
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché para archivos estáticos (JS, CSS, imágenes)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # No cachear el index.html para asegurar que siempre carguen la última versión del JS
    location = /index.html {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
