# Conversation states for the ConversationHandler
(EMAIL, PASSWORD, MAIN_MENU, APPOINTMENT_EMAIL, EDIT_OR_NEW_APPOINTMENT,
 APPOINTMENT_PASSWORD, IVR, CONSULATE, NEED_CAS, CONSULATE_ASC, MIN_DATE, MAX_DATE,
 SELECT_APPOINTMENT, CONFIRM_DELETE, SCHEDULE_SELECT, MANUAL_SCHEDULE_ID) = range(16)
