(EMAIL, PASSWORD, MAIN_MENU, APPOINTMENT_EMAIL, EDIT_OR_NEW_APPOINTMENT,
 APPOINTMENT_PASSWORD, IVR, CONSULATE, NEED_CAS, CONSULATE_ASC, MIN_DATE, MAX_DATE,
 SELECT_APPOINTMENT, CONFIRM_DELETE, SCHEDULE_SELECT, MANUAL_SCHEDULE_ID, SELECT_COUNTRY,
 ADMIN_CREATE_USER_NAME, ADMIN_CREATE_USER_EMAIL, ADMIN_CREATE_USER_PASS, ADMIN_CREATE_USER_WHATSAPP) = range(21)
