# Conversation states for the ConversationHandler
(EMAIL, PASSWORD, MAIN_MENU, APPOINTMENT_EMAIL, EDIT_OR_NEW_APPOINTMENT,
 APPOINTMENT_PASSWORD, IVR, CONSULATE, CONSULATE_ASC, MIN_DATE, MAX_DATE,
 SELECT_APPOINTMENT, CONFIRM_DELETE) = range(13)
